version: '3.7'

services:
  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    command: server /data
    networks:
      - app_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: ["start-dev"]
    networks:
      - app_network


  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - KEYCLOAK_URL=http://keycloak:8080
    ports:
      - "5000:5000"
    depends_on:
      - minio
      - keycloak
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  minio_data:
